<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en"><head>
  
  <meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
    integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
	
  <title><?= $this->escapeHtml($title); ?></title>

</head>
<body style="padding-top: 5rem;">
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">

	<a class="navbar-brand" href="#">Syscorpious TI</a> 
	<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" 
	  aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="navbar-collapse collapse " id="navbarsExampleDefault">
	<ul class="navbar-nav mr-auto">
		<li class="nav-item"> <a class="nav-link" href="home.html"> Home </a></li>
		<li class="nav-item"> <a class="nav-link" href="services.html"> Serviços </a> </li>
		<li class="nav-item"> <a class="nav-link" href="contact.html"> Contato </a></li>
	</ul>
	</div>
	
</nav>

<div class="container">
	<h1>Bootstrap starter template</h1>
    <div class="row">
		<div class="col-md-9">
			<h1>Left Pane</h1>
			<div id="display">
			</div>
		</div>
		<div class="col-md-3">
			<button type="button" class="dropdown-toggle" data-toggle="collapse" data-target="#demo"></button>
			<div id="demo" class="collapse in">Testing collapsing content </div>
			<div class="card my-3">
				<h5 class="card-header">Serviços</h5>
				<div class="card-body">
					<div class="row">
						<div class="col-md-6">
							<ul class="list-unstyled mb-0">
							<?php foreach($list as $item) : ?>
							<li><?= $this->escapeHtml($item); ?></li>
		                    <?php endforeach; ?>
		                    </ul>
						</div>
						<div class="col-md-6">
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
</body>
</html>